apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: monitoring
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: '>=1.10.0 <100.0.0'
    helm:
      values: |
        fullnameOverride: tempo

        tempo:
          # Minimal monolithic config with OTLP receivers
          server:
            http_listen_port: 3100
          distributor:
            receivers:
              otlp:
                protocols:
                  http:
                    endpoint: 0.0.0.0:4318
                  grpc:
                    endpoint: 0.0.0.0:4317
          storage:
            trace:
              backend: local
              wal:
                path: /var/tempo/wal
              local:
                path: /var/tempo/traces

        persistence:
          enabled: false  # demo; enable + storageClass for prod

        service:
          otlp:
            enabled: true
            grpc:
              enabled: true
              servicePort: 4317
            http:
              enabled: true
              servicePort: 4318
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
