apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: Platform monitoring stack
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
